// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@example.com"
        },
        "license": {
            "name": "MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Healthcheck",
                "responses": {
                    "200": {
                        "description": "status: ok",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/http.APIResponse"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "type": "object",
                                            "additionalProperties": {
                                                "type": "string"
                                            }
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "http.APIError": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "kode error ringkas (mis: VALIDATION_ERROR, NOT_FOUND)",
                    "type": "string"
                },
                "details": {
                    "description": "detail (bisa array field error, dsb.)"
                }
            }
        },
        "http.APIResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "description": "payload (opsional)"
                },
                "error": {
                    "description": "error (opsional)",
                    "allOf": [
                        {
                            "$ref": "#/definitions/http.APIError"
                        }
                    ]
                },
                "message": {
                    "description": "pesan singkat",
                    "type": "string"
                },
                "success": {
                    "description": "true jika sukses",
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{"http"},
	Title:            "BlogApp API",
	Description:      "REST API untuk BlogApp (Go + Next.js)",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
